
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    image: jliotorresmoreno/odoo:latest

    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
      - "8071:8071"

    volumes:
      - odoo_data:/var/lib/odoo
      - odoo_custom_addons:/opt/odoo/custom_addons
    restart: unless-stopped

volumes:
  db_data:
  odoo_data:
  odoo_custom_addons:
    driver: local
    driver_opts:
      type: none
      device: ./custom_addons
      o: bind