services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  service:
    build:
      context: .
      dockerfile: Dockerfile
    image: jliotorresmoreno/odoo:18.0
    depends_on:
      db:
        condition: service_healthy
      permissions-fix:
        condition: service_completed_successfully
    ports:
      - "0.0.0.0:8069:8069" # Binds to IPv4 only
      - "0.0.0.0:8072:8072" # Binds to IPv4 only
    environment:
      PGHOST: ${POSTGRES_HOST}
      PGPORT: ${POSTGRES_PORT}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      WORKERS: ${WORKERS}
      HTTP_PORT: ${HTTP_PORT}
      GEVENT_PORT: ${GEVENT_PORT}
      MAX_REQUESTS: ${MAX_REQUESTS}
      LIMIT_TIME_CPU: ${LIMIT_TIME_CPU}
      LIMIT_TIME_REAL: ${LIMIT_TIME_REAL}
      LIMIT_MEMORY_HARD: ${LIMIT_MEMORY_HARD}
      LIMIT_MEMORY_SOFT: ${LIMIT_MEMORY_SOFT}
      LONGPOLLING_INTERVAL: ${LONGPOLLING_INTERVAL}
      LOG_LEVEL: ${LOG_LEVEL}
      LIST_DB: ${LIST_DB}
    volumes:
      - odoo_data:/var/lib/odoo
      - odoo_custom_addons:/opt/odoo/custom_addons
    restart: unless-stopped

  admin:
    build:
      context: .
      dockerfile: Dockerfile
    image: jliotorresmoreno/odoo:18.0
    depends_on:
      db:
        condition: service_healthy
      permissions-fix:
        condition: service_completed_successfully
    ports:
      - "0.0.0.0:18069:8069" # Binds to IPv4 only
      - "0.0.0.0:18072:8072" # Binds to IPv4 only
    environment:
      PGHOST: ${POSTGRES_HOST}
      PGPORT: ${POSTGRES_PORT}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      WORKERS: ${WORKERS}
      HTTP_PORT: ${HTTP_PORT}
      GEVENT_PORT: ${GEVENT_PORT}
      MAX_REQUESTS: ${MAX_REQUESTS}
      LIMIT_TIME_CPU: ${LIMIT_TIME_CPU}
      LIMIT_TIME_REAL: ${LIMIT_TIME_REAL}
      LIMIT_MEMORY_HARD: ${LIMIT_MEMORY_HARD}
      LIMIT_MEMORY_SOFT: ${LIMIT_MEMORY_SOFT}
      LONGPOLLING_INTERVAL: ${LONGPOLLING_INTERVAL}
      LOG_LEVEL: ${LOG_LEVEL}
      LIST_DB: True
    volumes:
      - odoo_data:/var/lib/odoo
      - odoo_custom_addons:/opt/odoo/custom_addons
    restart: unless-stopped

  permissions-fix:
    image: busybox
    command: >
      sh -c "chown -R 1000:1000 /var/lib/odoo && chown -R 1000:1000 /backup"
    volumes:
      - odoo_data:/var/lib/odoo
      - backup_data:/backup
    restart: "no"
    user: root

volumes:
  backup_data:
    driver: local
    driver_opts:
      type: none
      device: ./backup
      o: bind
  db_data:
  odoo_data:
  odoo_custom_addons:
    driver: local
    driver_opts:
      type: none
      device: ./custom_addons
      o: bind