apiVersion: v1
kind: Service
metadata:
  name: odoo-admin-lb
spec:
  type: LoadBalancer
  selector:
    app: odoo
    role: admin
  ports:
    - name: service
      port: 18069
      targetPort: 8069
    - name: longpolling
      port: 18072
      targetPort: 8072
