apiVersion: v1
kind: Service
metadata:
  name: odoo-admin
spec:
  selector:
    app: odoo
    role: admin
  ports:
    - name: service
      port: 8069
      targetPort: 8069
    - name: longpolling
      port: 8072
      targetPort: 8072
  type: ClusterIP
