apiVersion: v1
kind: Service
metadata:
  name: odoo-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: odoo
    role: service
  ports:
    - name: http
      port: 8069
      targetPort: 8069
