apiVersion: v1
kind: Secret
metadata:
  name: odoo-secret
type: Opaque
stringData:
  ADMIN_PASSWORD: Vbc87mHjJta7vV4E
  POSTGRES_PASSWORD: odoo
  POSTGRES_DB: postgres
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_USER: odoo
  PGHOST: postgres
  PGPORT: "5432"
  PGUSER: odoo
  PGPASSWORD: odoo