apiVersion: v1
kind: Service
metadata:
  name: odoo-websocket-lb
spec:
  type: LoadBalancer
  selector:
    app: odoo
    role: websocket
  ports:
    - name: longpolling
      port: 8072
      targetPort: 8072
