apiVersion: v1
kind: Service
metadata:
  name: odoo-websocket
spec:
  selector:
    app: odoo
    role: websocket
  ports:
    - name: longpolling
      port: 8072
      targetPort: 8072
  type: ClusterIP
