apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-odoo-custom-addons
  namespace: odoo
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/odoo-custom-addons
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - juliotorres-pc


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-custom-addons
  namespace: odoo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-storage
